### ISSUE TITLE
The Github API fetching everything won't work.

### ISSUE THREAD

**Issue by aashutoshrathi** [JBossOutreach/gci#121]
### Description

The GitHub API URL we used to fetch no longer exists and gives 404.

### Reason

In the main.js file, we have used a URL through which we are using GitHub API.
That URL won't work anymore as we have shifted from `jboss-outreach` to `JBossOutreach`.

### Proposed Solution
In this issue, the assignee should replace all https://api.github.com/orgs/jboss-outreach/repos to https://api.github.com/orgs/JBossOutreach/repos.
This will make the GCI site work again.

**Comment by Ananthavijay** [comment]
will work on it @aashutoshrathi

**Comment by aashutoshrathi** [comment]
Go for it

**Comment by vijay35** [comment]
This [PR](https://github.com/JBossOutreach/gci/pull/122) fixes the issue

**Comment by Ananthavijay** [comment]
@aashutoshrathi  You can close the issue now :+1:
